#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}


function do_one {
	cp $1 inlist
	check_okay
	rm -rf $2
	echo 'run' $1
	./rn1
	check_okay
  if [ ! -r $2 ]
  then
  	echo
  	echo "******************************************************************"
  	echo 'failed to create' $2 'when running' $1
  	echo "******************************************************************"
  	echo
  	exit 1
  fi
  echo
  echo 'finished' $1
  echo
	echo '***'
	echo '***'
	echo '***'
	echo '***'
	echo '***'
	echo '***'
	echo
}

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
do_one inlist_evolve_22.5_0.05_0.24_0.02_0.5_9.0_0.1 irrad_22.5_0.05_0.24_0.02_0.5_9.0.mod
date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished all inlists for make_planets'

